name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --configuration release --filter Category\!=Integration --logger "trx;LogFilePrefix=net6.0" --results-directory "${{ github.workspace }}/TestResults" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --no-build --verbosity normal
    - name: Check test failure
      if: github.event_name == 'pull_request' && steps.tests.outcome != 'success'
      run: exit 1
    - name: Upload test coverage
      uses: codecov/codecov-action@v3
      with:
        flags: net6.0
    - name: Parse Trx files
      uses: NasAmin/trx-parser@v0.2.0
      id: trx-parser
      if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository # does not work on PRs from forks
      with:
        TRX_PATH: ${{ github.workspace }}/TestResults
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
